//! Stable `IpcError` construction.
//!
//! Every error crossing the IPC boundary carries a code, a category, a
//! retryable flag, the stage it happened in, a safe message and a concrete
//! action. "未知错误" is never produced.

use git_repo_migrator_application::IpcError;
use git_repo_migrator_domain::ErrorCategory;
use git_repo_migrator_local_store::StoreError;
use git_repo_migrator_platform_core::{PlatformError, PlatformErrorCategory};

pub fn error(
    code: &str,
    category: ErrorCategory,
    retryable: bool,
    stage: &str,
    safe_message: impl Into<String>,
    action: impl Into<String>,
) -> IpcError {
    IpcError {
        code: code.to_owned(),
        category,
        retryable,
        stage: stage.to_owned(),
        safe_message: safe_message.into(),
        action: action.into(),
    }
}

pub fn validation(
    stage: &str,
    safe_message: impl Into<String>,
    action: impl Into<String>,
) -> IpcError {
    error(
        "ipc.validation",
        ErrorCategory::Validation,
        false,
        stage,
        safe_message,
        action,
    )
}

pub fn conflict(
    stage: &str,
    safe_message: impl Into<String>,
    action: impl Into<String>,
) -> IpcError {
    error(
        "ipc.conflict",
        ErrorCategory::Conflict,
        false,
        stage,
        safe_message,
        action,
    )
}

pub fn unsupported(
    stage: &str,
    safe_message: impl Into<String>,
    action: impl Into<String>,
) -> IpcError {
    error(
        "ipc.unsupported",
        ErrorCategory::Unsupported,
        false,
        stage,
        safe_message,
        action,
    )
}

pub fn not_found(stage: &str, what: &str) -> IpcError {
    error(
        "ipc.not_found",
        ErrorCategory::Validation,
        false,
        stage,
        format!("找不到 {what}"),
        "请刷新界面后重新选择",
    )
}

pub fn store(stage: &str, source: &StoreError) -> IpcError {
    // `StoreError` messages are generated by our own code and rusqlite; they
    // never embed credentials because credentials are never bound as SQL
    // parameters.
    error(
        "ipc.store",
        ErrorCategory::Disk,
        true,
        stage,
        format!("本地状态库操作失败：{source}"),
        "请确认磁盘可写并重试；已完成的检查点不会丢失",
    )
}

pub fn from_platform(stage: &str, source: &PlatformError) -> IpcError {
    let category = match source.category {
        PlatformErrorCategory::Auth => ErrorCategory::Auth,
        PlatformErrorCategory::Permission => ErrorCategory::Permission,
        PlatformErrorCategory::Conflict => ErrorCategory::Conflict,
        PlatformErrorCategory::RateLimited => ErrorCategory::RateLimited,
        PlatformErrorCategory::Network => ErrorCategory::Network,
        PlatformErrorCategory::Validation => ErrorCategory::Validation,
        PlatformErrorCategory::Unsupported => ErrorCategory::Unsupported,
        PlatformErrorCategory::Verification => ErrorCategory::Verification,
    };
    IpcError {
        code: source.code.clone(),
        category,
        retryable: source.retryable,
        stage: stage.to_owned(),
        safe_message: source.safe_message.clone(),
        action: source.action.clone(),
    }
}

/// Categories that must never be retried automatically. Blind retries on these
/// either lock the account out or repeat a destructive remote write.
pub fn is_blind_retry_forbidden(category: ErrorCategory) -> bool {
    matches!(
        category,
        ErrorCategory::Auth
            | ErrorCategory::Permission
            | ErrorCategory::Conflict
            | ErrorCategory::Validation
            | ErrorCategory::Unsupported
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn auth_permission_and_conflict_are_never_blind_retried() {
        for category in [
            ErrorCategory::Auth,
            ErrorCategory::Permission,
            ErrorCategory::Conflict,
        ] {
            assert!(is_blind_retry_forbidden(category));
        }
        assert!(!is_blind_retry_forbidden(ErrorCategory::RateLimited));
        assert!(!is_blind_retry_forbidden(ErrorCategory::Network));
    }

    #[test]
    fn every_error_carries_a_code_and_an_action() {
        let value = validation("connection", "地址无效", "请输入 HTTPS 地址");
        assert!(!value.code.is_empty());
        assert!(!value.action.is_empty());
        assert!(!value.safe_message.contains("未知"));
    }

    #[test]
    fn platform_rate_limit_maps_to_a_retryable_ipc_error() {
        let source = PlatformError {
            code: "platform.rate_limited".into(),
            category: PlatformErrorCategory::RateLimited,
            retryable: true,
            safe_message: "请求过于频繁".into(),
            action: "等待限流窗口结束".into(),
            retry_after_seconds: Some(30),
        };
        let mapped = from_platform("discovery", &source);
        assert_eq!(mapped.category, ErrorCategory::RateLimited);
        assert!(mapped.retryable);
        assert_eq!(mapped.stage, "discovery");
    }
}
