[package]
name = "git-repo-migrator-platform-github"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1"
git-repo-migrator-platform-core = { path = "../platform-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"

[lints]
workspace = true
